#loads configuration file and selects lines needed
def load_config(file_name):
    lines=[]
    with open(file_name,'r') as f:
        for line in f:
            line=line.rstrip()
            if line !="" and not line.strip().startswith("//"):
                lines.append(line)
    return lines
# splits configuration into sections
def parse_config(config):
    sections={}
    current_section=None
    for line in config:
        if line.endswith(":") :
            current_section=line[:-1]
            sections[current_section]=[]
        else:
            sections[current_section].append(line.strip())
    return sections
# builds grammar
def build_grammar(config):
    sections=parse_config(config)

    variables=sections["Variables"]
    terminals=sections["Terminals"]
    start=sections["Start"][0]
    rules={}
# separates the rules and adds them to our dictionary
    for rule in sections["Rules"]:
        left,right=rule.split("->")
        left=left.strip()
        right=right.strip()
        if left not in rules:
            rules[left]=[]
        rules[left].append(right)
    return {
        "variables": variables,
        "terminals": terminals,
        "start": start,
        "rules": rules
    }
   # verifies if a word could be generated by the grammar
def verify_word(word,grammar):
    max_length=len(word)
    if word=='e' or word=="epsilon":
        word=""
    # we begin from the start symbol
    queue=[grammar["start"]]
    visited=set()
    while queue:
        current=queue.pop(0)
        if current==word:
            return True
        if current in visited:
            continue
        visited.add(current)
        # we stop if the number of terminals becomes too long
        if sum(1 for c in current if c in grammar["terminals"])>max_length:
            continue
        # replace the first variable (leftmost variable)
        for i, c in enumerate(current):
            if c in grammar["variables"]:
                for p in grammar["rules"][c]:
                    if p=='e':
                        new=current[:i]+current[i+1:]
                    else:
                        new=current[:i]+p+current[i+1:]
                    queue.append(new)
                break
    return False
